language: erlang

env:
  - LUA='Lua 5.1'
  - LUA='Lua 5.2'

before_install:
  - bash .travis_setup.sh

branches:
  only:
    - master

install:
  - sudo luarocks install busted

script: "busted spec"
