#! /usr/bin/sh

LUA_TREE='/usr/share/csagent'
export LUA_PATH="${LUA_TREE}/share/lua/5.2/?.lua;$LUA_TREE/share/lua/5.2/?/init.lua;/usr/share/lua/5.2/?.lua;/usr/share/lua/5.2/?/init.lua;/usr/lib/lua/5.2/?.lua;/usr/lib/lua/5.2/?/init.lua;./?.lua;/home/amr/.luarocks/share/lua/5.2/?.lua;/home/amr/.luarocks/share/lua/5.2/?/init.lua"

lua "$LUA_TREE/csagent.lua"
